[2024-09-29T20:47:13.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T20:47:13.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_stg_yellow_tripdata manual__2024-09-29T20:45:28.356121+00:00 [queued]>
[2024-09-29T20:47:13.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_stg_yellow_tripdata manual__2024-09-29T20:45:28.356121+00:00 [queued]>
[2024-09-29T20:47:13.826+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-09-29T20:47:13.839+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_stg_yellow_tripdata> on 2024-09-29 20:45:28.356121+00:00
[2024-09-29T20:47:13.846+0000] {standard_task_runner.py:63} INFO - Started process 253 to run task
[2024-09-29T20:47:13.849+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_stg_yellow_tripdata', 'manual__2024-09-29T20:45:28.356121+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpuq_8saxm']
[2024-09-29T20:47:13.851+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask dbt_staging_layer.dbt_run_stg_yellow_tripdata
[2024-09-29T20:47:13.898+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_stg_yellow_tripdata manual__2024-09-29T20:45:28.356121+00:00 [running]> on host c117e05af260
[2024-09-29T20:47:13.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_stg_yellow_tripdata' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T20:45:28.356121+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T20:45:28.356121+00:00'
[2024-09-29T20:47:13.989+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T20:47:14.001+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T20:47:14.002+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models stg_yellow_tripdata']
[2024-09-29T20:47:14.017+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T20:47:17.011+0000] {subprocess.py:93} INFO - [0m20:47:17  Running with dbt=1.8.0
[2024-09-29T20:47:17.376+0000] {subprocess.py:93} INFO - [0m20:47:17  Registered adapter: postgres=1.8.0
[2024-09-29T20:47:17.806+0000] {subprocess.py:93} INFO - [0m20:47:17  Unable to do partial parsing because of a version mismatch
[2024-09-29T20:47:20.176+0000] {subprocess.py:93} INFO - [0m20:47:20  [[33mWARNING[0m]: Deprecated functionality
[2024-09-29T20:47:20.177+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-09-29T20:47:20.177+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-09-29T20:47:20.177+0000] {subprocess.py:93} INFO - information.
[2024-09-29T20:47:20.547+0000] {subprocess.py:93} INFO - [0m20:47:20  Encountered an error:
[2024-09-29T20:47:20.548+0000] {subprocess.py:93} INFO - Compilation Error
[2024-09-29T20:47:20.548+0000] {subprocess.py:93} INFO -   Model 'model.fact_trip.stg_yellow_tripdata' (models/Staging/stg_yellow_tripdata.sql) depends on a source named 'staging.yellow_trip' which was not found
[2024-09-29T20:47:26.536+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-29T20:47:26.537+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T20:47:26.547+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-29T20:47:26.551+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_stg_yellow_tripdata, run_id=manual__2024-09-29T20:45:28.356121+00:00, execution_date=20240929T204528, start_date=20240929T204713, end_date=20240929T204726
[2024-09-29T20:47:26.563+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task dbt_staging_layer.dbt_run_stg_yellow_tripdata (Bash command failed. The command returned a non-zero exit code 2.; 253)
[2024-09-29T20:47:26.610+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-29T20:47:26.628+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T20:47:26.629+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
