[2024-10-12T09:00:04.835+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T09:00:04.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.move_files_to_archive scheduled__2024-10-12T08:45:00+00:00 [queued]>
[2024-10-12T09:00:04.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.move_files_to_archive scheduled__2024-10-12T08:45:00+00:00 [queued]>
[2024-10-12T09:00:04.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-12T09:00:04.876+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): move_files_to_archive> on 2024-10-12 08:45:00+00:00
[2024-10-12T09:00:04.883+0000] {standard_task_runner.py:63} INFO - Started process 89 to run task
[2024-10-12T09:00:04.886+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'move_files_to_archive', 'scheduled__2024-10-12T08:45:00+00:00', '--job-id', '528', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpcrpkid6p']
[2024-10-12T09:00:04.889+0000] {standard_task_runner.py:91} INFO - Job 528: Subtask move_files_to_archive
[2024-10-12T09:00:04.930+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.move_files_to_archive scheduled__2024-10-12T08:45:00+00:00 [running]> on host f02ce4f01a3b
[2024-10-12T09:00:05.014+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='move_files_to_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T08:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-12T08:45:00+00:00'
[2024-10-12T09:00:05.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T09:00:05.042+0000] {taxi_trip.py:128} ERROR - Error in archiving files
Traceback (most recent call last):
  File "/opt/airflow/dags/taxi_trip.py", line 120, in archiving
    archive_files = archive_green + archive_yellow
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[2024-10-12T09:00:05.043+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-12T09:00:05.043+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T09:00:05.054+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Taxi_trip_pipeline, task_id=move_files_to_archive, run_id=scheduled__2024-10-12T08:45:00+00:00, execution_date=20241012T084500, start_date=20241012T090004, end_date=20241012T090005
[2024-10-12T09:00:05.098+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-12T09:00:05.128+0000] {taskinstance.py:3498} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-10-12T09:00:05.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
