[2024-10-12T10:15:07.486+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T10:15:07.515+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T10:00:00+00:00 [queued]>
[2024-10-12T10:15:07.530+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T10:00:00+00:00 [queued]>
[2024-10-12T10:15:07.530+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-12T10:15:07.549+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_transformation_layer.dbt_run_model_green_trip> on 2024-10-12 10:00:00+00:00
[2024-10-12T10:15:07.559+0000] {standard_task_runner.py:63} INFO - Started process 670 to run task
[2024-10-12T10:15:07.562+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_transformation_layer.dbt_run_model_green_trip', 'scheduled__2024-10-12T10:00:00+00:00', '--job-id', '610', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpinduqkih']
[2024-10-12T10:15:07.565+0000] {standard_task_runner.py:91} INFO - Job 610: Subtask dbt_transformation_layer.dbt_run_model_green_trip
[2024-10-12T10:15:07.622+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T10:00:00+00:00 [running]> on host cb13d84d2d77
[2024-10-12T10:15:07.763+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_transformation_layer.dbt_run_model_green_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-12T10:00:00+00:00'
[2024-10-12T10:15:07.765+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T10:15:07.780+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-12T10:15:07.782+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models green_trip']
[2024-10-12T10:15:07.801+0000] {subprocess.py:86} INFO - Output:
[2024-10-12T10:15:11.107+0000] {subprocess.py:93} INFO - [0m10:15:11  Running with dbt=1.8.0
[2024-10-12T10:15:11.559+0000] {subprocess.py:93} INFO - [0m10:15:11  Registered adapter: postgres=1.8.0
[2024-10-12T10:15:12.014+0000] {subprocess.py:93} INFO - [0m10:15:12  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-12T10:15:12.015+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-12T10:15:12.015+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-12T10:15:12.015+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-12T10:15:12.304+0000] {subprocess.py:93} INFO - [0m10:15:12  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-12T10:15:12.307+0000] {subprocess.py:93} INFO - [0m10:15:12
[2024-10-12T10:15:12.456+0000] {subprocess.py:93} INFO - [0m10:15:12  Concurrency: 3 threads (target='dev')
[2024-10-12T10:15:12.457+0000] {subprocess.py:93} INFO - [0m10:15:12
[2024-10-12T10:15:12.468+0000] {subprocess.py:93} INFO - [0m10:15:12  1 of 1 START sql view model analysis.green_trip ................................ [RUN]
[2024-10-12T10:15:12.654+0000] {subprocess.py:93} INFO - [0m10:15:12  1 of 1 OK created sql view model analysis.green_trip ........................... [[32mCREATE VIEW[0m in 0.18s]
[2024-10-12T10:15:12.666+0000] {subprocess.py:93} INFO - [0m10:15:12
[2024-10-12T10:15:12.667+0000] {subprocess.py:93} INFO - [0m10:15:12  Finished running 1 view model in 0 hours 0 minutes and 0.36 seconds (0.36s).
[2024-10-12T10:15:12.718+0000] {subprocess.py:93} INFO - [0m10:15:12
[2024-10-12T10:15:12.719+0000] {subprocess.py:93} INFO - [0m10:15:12  [32mCompleted successfully[0m
[2024-10-12T10:15:12.719+0000] {subprocess.py:93} INFO - [0m10:15:12
[2024-10-12T10:15:12.720+0000] {subprocess.py:93} INFO - [0m10:15:12  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-12T10:15:13.939+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-12T10:15:13.940+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T10:15:13.962+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Taxi_trip_pipeline, task_id=dbt_transformation_layer.dbt_run_model_green_trip, run_id=scheduled__2024-10-12T10:00:00+00:00, execution_date=20241012T100000, start_date=20241012T101507, end_date=20241012T101513
[2024-10-12T10:15:13.991+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-12T10:15:14.018+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-12T10:15:14.019+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-12T10:22:30.062+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T10:22:30.085+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T10:00:00+00:00 [queued]>
[2024-10-12T10:22:30.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T10:00:00+00:00 [queued]>
[2024-10-12T10:22:30.094+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-12T10:22:30.108+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_transformation_layer.dbt_run_model_green_trip> on 2024-10-12 10:00:00+00:00
[2024-10-12T10:22:30.116+0000] {standard_task_runner.py:63} INFO - Started process 74 to run task
[2024-10-12T10:22:30.120+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_transformation_layer.dbt_run_model_green_trip', 'scheduled__2024-10-12T10:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpk4ic3ycq']
[2024-10-12T10:22:30.122+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask dbt_transformation_layer.dbt_run_model_green_trip
[2024-10-12T10:22:30.181+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_transformation_layer.dbt_run_model_green_trip scheduled__2024-10-12T10:00:00+00:00 [running]> on host bcbc9bb54b17
[2024-10-12T10:22:30.270+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_transformation_layer.dbt_run_model_green_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-12T10:00:00+00:00'
[2024-10-12T10:22:30.272+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T10:22:30.285+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-12T10:22:30.285+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models green_trip']
[2024-10-12T10:22:30.301+0000] {subprocess.py:86} INFO - Output:
[2024-10-12T10:22:33.398+0000] {subprocess.py:93} INFO - [0m10:22:33  Running with dbt=1.8.0
[2024-10-12T10:22:33.760+0000] {subprocess.py:93} INFO - [0m10:22:33  Registered adapter: postgres=1.8.0
[2024-10-12T10:22:34.231+0000] {subprocess.py:93} INFO - [0m10:22:34  Unable to do partial parsing because profile has changed
[2024-10-12T10:22:36.451+0000] {subprocess.py:93} INFO - [0m10:22:36  [[33mWARNING[0m]: Deprecated functionality
[2024-10-12T10:22:36.452+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-12T10:22:36.452+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-12T10:22:36.453+0000] {subprocess.py:93} INFO - information.
[2024-10-12T10:22:36.892+0000] {subprocess.py:93} INFO - [0m10:22:36  [[33mWARNING[0m]: Found patch for macro "payment_type_mapping" which was not found
[2024-10-12T10:22:36.894+0000] {subprocess.py:93} INFO - [0m10:22:36  [[33mWARNING[0m]: Found patch for macro "rate_code_mapping" which was not found
[2024-10-12T10:22:36.895+0000] {subprocess.py:93} INFO - [0m10:22:36  [[33mWARNING[0m]: Found patch for macro "store_and_fwd_flag_mapping" which was not found
[2024-10-12T10:22:36.897+0000] {subprocess.py:93} INFO - [0m10:22:36  [[33mWARNING[0m]: Found patch for macro "trip_type_mapping" which was not found
[2024-10-12T10:22:36.900+0000] {subprocess.py:93} INFO - [0m10:22:36  [[33mWARNING[0m]: Found patch for macro "vendor_mapping" which was not found
[2024-10-12T10:22:37.042+0000] {subprocess.py:93} INFO - [0m10:22:37  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-12T10:22:37.043+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-12T10:22:37.043+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-12T10:22:37.043+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-12T10:22:37.256+0000] {subprocess.py:93} INFO - [0m10:22:37  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-12T10:22:37.260+0000] {subprocess.py:93} INFO - [0m10:22:37
[2024-10-12T10:22:37.440+0000] {subprocess.py:93} INFO - [0m10:22:37  Concurrency: 3 threads (target='dev')
[2024-10-12T10:22:37.443+0000] {subprocess.py:93} INFO - [0m10:22:37
[2024-10-12T10:22:37.459+0000] {subprocess.py:93} INFO - [0m10:22:37  1 of 1 START sql view model analysis.green_trip ................................ [RUN]
[2024-10-12T10:22:37.626+0000] {subprocess.py:93} INFO - [0m10:22:37  1 of 1 ERROR creating sql view model analysis.green_trip ....................... [[31mERROR[0m in 0.16s]
[2024-10-12T10:22:37.650+0000] {subprocess.py:93} INFO - [0m10:22:37
[2024-10-12T10:22:37.651+0000] {subprocess.py:93} INFO - [0m10:22:37  Finished running 1 view model in 0 hours 0 minutes and 0.39 seconds (0.39s).
[2024-10-12T10:22:37.740+0000] {subprocess.py:93} INFO - [0m10:22:37
[2024-10-12T10:22:37.741+0000] {subprocess.py:93} INFO - [0m10:22:37  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-12T10:22:37.742+0000] {subprocess.py:93} INFO - [0m10:22:37
[2024-10-12T10:22:37.743+0000] {subprocess.py:93} INFO - [0m10:22:37    Database Error in model green_trip (models/Staging/green_trip.sql)
[2024-10-12T10:22:37.743+0000] {subprocess.py:93} INFO -   relation "public.green_trip" does not exist
[2024-10-12T10:22:37.743+0000] {subprocess.py:93} INFO -   LINE 17:     FROM "nyc_taxi_trip"."public"."green_trip"
[2024-10-12T10:22:37.743+0000] {subprocess.py:93} INFO -                     ^
[2024-10-12T10:22:37.743+0000] {subprocess.py:93} INFO -   compiled code at target/run/fact_trip/models/Staging/green_trip.sql
[2024-10-12T10:22:37.744+0000] {subprocess.py:93} INFO - [0m10:22:37
[2024-10-12T10:22:37.744+0000] {subprocess.py:93} INFO - [0m10:22:37  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-12T10:22:39.030+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-12T10:22:39.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T10:22:39.043+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-12T10:22:39.047+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_transformation_layer.dbt_run_model_green_trip, run_id=scheduled__2024-10-12T10:00:00+00:00, execution_date=20241012T100000, start_date=20241012T102230, end_date=20241012T102239
[2024-10-12T10:22:39.063+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task dbt_transformation_layer.dbt_run_model_green_trip (Bash command failed. The command returned a non-zero exit code 1.; 74)
[2024-10-12T10:22:39.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-12T10:22:39.106+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T10:22:39.108+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
