[2024-09-29T20:47:13.829+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T20:47:13.855+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_stg_green_tripdata manual__2024-09-29T20:45:28.356121+00:00 [queued]>
[2024-09-29T20:47:13.865+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_stg_green_tripdata manual__2024-09-29T20:45:28.356121+00:00 [queued]>
[2024-09-29T20:47:13.865+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-09-29T20:47:13.878+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_stg_green_tripdata> on 2024-09-29 20:45:28.356121+00:00
[2024-09-29T20:47:13.885+0000] {standard_task_runner.py:63} INFO - Started process 255 to run task
[2024-09-29T20:47:13.889+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_stg_green_tripdata', 'manual__2024-09-29T20:45:28.356121+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmppd31xl6g']
[2024-09-29T20:47:13.892+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask dbt_staging_layer.dbt_run_stg_green_tripdata
[2024-09-29T20:47:13.940+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_stg_green_tripdata manual__2024-09-29T20:45:28.356121+00:00 [running]> on host c117e05af260
[2024-09-29T20:47:14.030+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_stg_green_tripdata' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T20:45:28.356121+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T20:45:28.356121+00:00'
[2024-09-29T20:47:14.031+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T20:47:14.048+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T20:47:14.049+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models stg_green_tripdata']
[2024-09-29T20:47:14.065+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T20:47:17.080+0000] {subprocess.py:93} INFO - [0m20:47:17  Running with dbt=1.8.0
[2024-09-29T20:47:17.446+0000] {subprocess.py:93} INFO - [0m20:47:17  Registered adapter: postgres=1.8.0
[2024-09-29T20:47:17.763+0000] {subprocess.py:93} INFO - [0m20:47:17  Unable to do partial parsing because of a version mismatch
[2024-09-29T20:47:20.073+0000] {subprocess.py:93} INFO - [0m20:47:20  [[33mWARNING[0m]: Deprecated functionality
[2024-09-29T20:47:20.073+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-09-29T20:47:20.074+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-09-29T20:47:20.074+0000] {subprocess.py:93} INFO - information.
[2024-09-29T20:47:20.464+0000] {subprocess.py:93} INFO - [0m20:47:20  Encountered an error:
[2024-09-29T20:47:20.464+0000] {subprocess.py:93} INFO - Compilation Error
[2024-09-29T20:47:20.464+0000] {subprocess.py:93} INFO -   Model 'model.fact_trip.stg_yellow_tripdata' (models/Staging/stg_yellow_tripdata.sql) depends on a source named 'staging.yellow_trip' which was not found
[2024-09-29T20:47:21.532+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-29T20:47:21.533+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T20:47:21.543+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-29T20:47:21.546+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_stg_green_tripdata, run_id=manual__2024-09-29T20:45:28.356121+00:00, execution_date=20240929T204528, start_date=20240929T204713, end_date=20240929T204721
[2024-09-29T20:47:21.558+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task dbt_staging_layer.dbt_run_stg_green_tripdata (Bash command failed. The command returned a non-zero exit code 2.; 255)
[2024-09-29T20:47:21.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-29T20:47:21.627+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T20:47:21.628+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
