[2024-10-01T06:38:37.253+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T06:38:37.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_yellow_trip scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-01T06:38:37.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_yellow_trip scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-01T06:38:37.289+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-01T06:38:37.303+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_yellow_trip> on 2024-09-30 00:00:00+00:00
[2024-10-01T06:38:37.310+0000] {standard_task_runner.py:63} INFO - Started process 154 to run task
[2024-10-01T06:38:37.313+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_yellow_trip', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpa3milkho']
[2024-10-01T06:38:37.316+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask dbt_staging_layer.dbt_run_yellow_trip
[2024-10-01T06:38:37.361+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_yellow_trip scheduled__2024-09-30T00:00:00+00:00 [running]> on host fcb0f9e87e2b
[2024-10-01T06:38:37.439+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_yellow_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-10-01T06:38:37.440+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T06:38:37.453+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T06:38:37.453+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models yellow_trip']
[2024-10-01T06:38:37.466+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T06:38:40.280+0000] {subprocess.py:93} INFO - [0m06:38:40  Running with dbt=1.8.0
[2024-10-01T06:38:40.620+0000] {subprocess.py:93} INFO - [0m06:38:40  Registered adapter: postgres=1.8.0
[2024-10-01T06:38:41.121+0000] {subprocess.py:93} INFO - [0m06:38:41  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-01T06:38:41.121+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-01T06:38:41.122+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-01T06:38:41.122+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-01T06:38:41.402+0000] {subprocess.py:93} INFO - [0m06:38:41  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-01T06:38:41.405+0000] {subprocess.py:93} INFO - [0m06:38:41
[2024-10-01T06:38:41.590+0000] {subprocess.py:93} INFO - [0m06:38:41  Concurrency: 3 threads (target='dev')
[2024-10-01T06:38:41.591+0000] {subprocess.py:93} INFO - [0m06:38:41
[2024-10-01T06:38:41.606+0000] {subprocess.py:93} INFO - [0m06:38:41  1 of 1 START sql view model analysis.yellow_trip ............................... [RUN]
[2024-10-01T06:38:41.766+0000] {subprocess.py:93} INFO - [0m06:38:41  1 of 1 ERROR creating sql view model analysis.yellow_trip ...................... [[31mERROR[0m in 0.16s]
[2024-10-01T06:38:41.777+0000] {subprocess.py:93} INFO - [0m06:38:41
[2024-10-01T06:38:41.778+0000] {subprocess.py:93} INFO - [0m06:38:41  Finished running 1 view model in 0 hours 0 minutes and 0.37 seconds (0.37s).
[2024-10-01T06:38:41.851+0000] {subprocess.py:93} INFO - [0m06:38:41
[2024-10-01T06:38:41.852+0000] {subprocess.py:93} INFO - [0m06:38:41  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-01T06:38:41.853+0000] {subprocess.py:93} INFO - [0m06:38:41
[2024-10-01T06:38:41.854+0000] {subprocess.py:93} INFO - [0m06:38:41    Database Error in model yellow_trip (models/Staging/yellow_trip.sql)
[2024-10-01T06:38:41.854+0000] {subprocess.py:93} INFO -   column "vendorid" does not exist
[2024-10-01T06:38:41.854+0000] {subprocess.py:93} INFO -   LINE 12:     row_number() over(partition by vendorid, tpep_pickup_dat...
[2024-10-01T06:38:41.855+0000] {subprocess.py:93} INFO -                                               ^
[2024-10-01T06:38:41.855+0000] {subprocess.py:93} INFO -   HINT:  Perhaps you meant to reference the column "yellow_trip.VendorID".
[2024-10-01T06:38:41.855+0000] {subprocess.py:93} INFO -   compiled code at target/run/fact_trip/models/Staging/yellow_trip.sql
[2024-10-01T06:38:41.855+0000] {subprocess.py:93} INFO - [0m06:38:41
[2024-10-01T06:38:41.856+0000] {subprocess.py:93} INFO - [0m06:38:41  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-01T06:38:42.866+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T06:38:42.867+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T06:38:42.878+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T06:38:42.885+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_yellow_trip, run_id=scheduled__2024-09-30T00:00:00+00:00, execution_date=20240930T000000, start_date=20241001T063837, end_date=20241001T063842
[2024-10-01T06:38:42.901+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task dbt_staging_layer.dbt_run_yellow_trip (Bash command failed. The command returned a non-zero exit code 1.; 154)
[2024-10-01T06:38:42.935+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T06:38:42.959+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T06:38:42.960+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
